### PR TITLE
Clone of korels repository

### PR DESCRIPTION
**Pull request by KorelU**
Copies over the markdown files I made. (Server.md, BasicNetworkConfiguration.md, Install the DENT NOS on GNS3.md, and index.md)

NOTE: Credit to Royal for the following file (LocalMachine.md)

Signed-off-by: Korel Ucpinar <Korelucpinar@gmail.com>

### CODE REVIEW

**Comment by taraschornyiplv** [comment]
@KorelU  can you please fix DCO error and add description to your commits

**Comment by KorelU** [comment]
Closed pull request because DCO error and comment descriptions were added by Royal

**Comment by KorelU** [comment]
> @KorelU can you please fix DCO error and add description to your commits

Should now be Addressed

**Review by taraschornyiplv — DISMISSED** [review]

**Comment by KorelU** [comment]
As a point of note Taras, the changes you recommended to Royal in the previous PR he will be implementing in the following pull request which covers his contributions.

**Pull request merged**
