### PR TITLE
Includes DENT Installation Guide

### PR DESCRIPTION
**Pull request by KorelU**
This commit includes the documentation for the DENT installation guide. Reference: https://github.com/dentproject/dentOS/wiki/Installation

Images file locations were changed to permit separation in directories "DENT Installation" and "GNS3 Installation"

### CODE REVIEW

**Comment by royalpinto007** [comment]
Is there a specific use case for the .idea folder here? I believe it's IDE-based. 
You may have accidentally pushed those files, and they are not necessary in this context. 
Could you please confirm? @KorelU

**Comment by taskin0003** [comment]
Needs spell checking. For example "The dentOS build system generates **an** ONIE-compatible ..."

**Comment by KorelU** [comment]
> Needs spell checking.

Should now be addressed along with addition file issue

**Comment by KorelU** [comment]
Will address spelling changes and additional files then create new pull request.

**Pull request closed without merging**
